### ISSUE TITLE
"Skiers left" goes below zero

### ISSUE THREAD

**Issue by martey** [basicallydan/skifree.js#1]
I tested this on Google Chrome 24.0.1312.56 and Firefox 10.0.2.

The result is that the game never ends, but the skiers left continues to decrease.

This was hard for me to test, as the animation of the abominable snow monster eating the skier is really well done. I will probably have nightmares.

**Comment by Ember-RP** [comment]
Hi,

This appears to be the commit mentioned https://github.com/basicallydan/skifree.js/commit/0fdb414ee24be659f94bd69c78af30ace039ec49

I see the fix, it was quite simple! It appears you didn't need to reset anything at all.

Great job on skifree.js!
