### ISSUE TITLE
Too many trees in Firefox

### ISSUE THREAD

**Issue by toupeira** [basicallydan/skifree.js#13]
I'm using Firefox Aurora 28.0a2 on Debian sid. At the beginning there's always an impossible forest of trees:

![screenshot-2014-01-18-14 49 24 856985970](https://f.cloud.github.com/assets/6501/1947260/e713b7fa-8047-11e3-8895-f75161661eb4.png)

This doesn't happen on Chromium for some reason.

**Comment by katerberg** [comment]
This looks fixed to me as well.

**Comment by toupeira** [comment]
Yep looks fine now :+1: Sorry for not confirming earlier!

**Comment by basicallydan** [comment]
That's cool thanks for responding @katerberg and @toupeira :)
