### ISSUE TITLE
Error On Click

### ISSUE THREAD

**Issue by fpcorso** [basicallydan/skifree.js#21]
I am receiving a "Uncaught TypeError: Cannot read property 'x' of undefined" when left clicking. It points to this part:
https://github.com/basicallydan/skifree.js/blob/master/js/main.js#L250

**Comment by basicallydan** [comment]
Good spot, @fpcorso. Which browser were you using when this happened?

**Comment by fpcorso** [comment]
I am using Google Chrome Version 40.0.2214.115 (64-bit) on Linux (Elementary OS variant of Ubuntu).
